---
title: 'Homework #5'
author: "Rachel Brady"
date: "2023-11-28"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Packages
```{r get packages}
library(readr)
library(tidyverse)
library(purrr)
library(broom)
library(ggplot2)
library(ggthemes)
library(lubridate)
library(stringr)
```

# Get data, filter to one city
```{r get dataset}
get_homicide <- paste0("https://raw.githubusercontent.com/washingtonpost/",
                       "data-homicides/master/homicide-data.csv")

homicide <- read_csv(get_homicide) %>% 
  mutate(city_name = (paste(city, state, sep=", ")))

balt <- homicide %>% 
  filter(city_name == "Baltimore, MD" )
```

# Get data ready for plotting

```{r}
balt2 <- balt %>% 
  mutate(reported_date = ymd(reported_date)) %>% 
  mutate(year = substr(reported_date, 1,4)) %>% 
  mutate(mo = substr(reported_date, 6,7)) %>% 
  select(reported_date, year, mo) %>% 
  group_by(year, mo) %>% 
  summarize(monthly_count = n()) %>% 
  mutate(date = paste0(year, mo, sep = "01")) %>% 
  mutate(date = ymd(date)) %>% 
  mutate(season = case_when(mo %in% c("05", "06", "07", "08", "09", "10") ~ "Summer",
                            mo %in% c("11", "12", "01", "02", "03", "04") ~ "Winter"))
```

# Plotting
```{r fig.width = 10, fig.height = 3}
color <- c("#CCCCCC","#99CCFF", "white") #making color scheme

vline.data <- data.frame(z=c("2015-04-01"))
vline.data <- vline.data %>% 
  mutate(z = ymd(z)) #getting date set for vertical line

balt2 %>% 
  ggplot() +
  geom_col(aes(x = date, y = monthly_count, fill = season)) +
  geom_smooth(aes(x = date, y = monthly_count), color = "#6666FF", se = FALSE,
              span = 0.1, linewidth = 1.5) + 
  theme_dark() +
  scale_fill_manual(values= color) +
  labs(title = "Homicides in Baltimore, MD",
       x = "Date",
       y = "Monthly homicides") +
  theme(legend.position = "bottom") +
  theme(legend.title=element_blank()) +
  geom_vline(aes(xintercept = z), color = "#CC0000", linewidth = 2,
             linetype = "dashed", vline.data) +
  annotate("text", x = ymd("2014-08-01"), y = 40, 
           label = "        Arrest of \n Freddie Grey", 
           color = "white")
```


